import Head from 'next/head'
import styles from '../../styles/Style.module.css'
import AboutSec from '../../components/AboutSec'
import { SpaceBr } from '../../components/Space'



const Privacy =()=> {
  return (
    <main className={styles.PrivacyPage}>
      <Head>
        <title>RankLogo</title>
        <meta name="description" content="Generated by create next app" />  
      </Head>

      <AboutSec
        BackgroundImage= ""
        Title={["Privacy Policy"]}
        SubTitle={["BACKGROUND:"]}
        Para={["SketchProfs understands that your privacy is important to you and that you care about how your personal data is used and shared online. We respect and value the privacy of everyone who visits this website, www.RankLogo.com (“Our Site”) and will only collect and use personal data in ways that are described here, and in a manner that is consistent with Our obligations and your rights under the law.",
        <SpaceBr/>, 
        "Please read this Privacy Policy carefully and ensure that you understand it. Your acceptance of Our Privacy Policy is deemed to occur upon your first use of Our Site. If you do not accept and agree with this Privacy Policy, you must stop using Our Site immediately."
        ,<SpaceBr/>,
        <h2><span>1. Definitions and Interpretation</span></h2>,
        ,<SpaceBr/>,
        "In this Policy, the following terms shall have the following meanings: “Account” means an account required to access and/or use certain areas and features of Our Site; “Cookie” means a small text file placed on your computer or device by Our Site when you visit certain parts of Our Site and/or when you use certain features of Our Site. Details of the Cookies used by Our Site are set out in section 12, below;"
        ,<SpaceBr/>,
        ,<h2><span>2. Information About Us</span></h2>,
        ,<SpaceBr/>,
        "2.1 Our Site is operated by SketchProfs"
        ,<SpaceBr/>,
    
        ,<SpaceBr/>,
        ,<h2><span>3. What Does This Policy Cover?</span></h2>,
        ,<SpaceBr/>,
        "This Privacy Policy applies only to your use of Our Site. Our Site may contain links to other websites. Please note that We have no control over how your data is collected, stored, or used by other websites and We advise you to check the privacy policies of any such websites before providing any data to them."
        ,<SpaceBr/>,
    
    
        ,<SpaceBr/>,
        ,<h2><span>4. Your Rights</span></h2>,
        ,<SpaceBr/>,
        "4.1 As a data subject, you have the following rights under the GDPR, which this Policy and Our use of personal data have been designed to uphold:",
        "4.1.1 The right to be informed about Our collection and use of personal data;",
        "4.1.2 The right of access to the personal data We hold about you (see section 12);",
        "4.1.3 The right to rectification if any personal data We hold about you is inaccurate or incomplete (please contact Us using the details in section 13);",
        "4.1.4 The right to be forgotten – i.e. the right to ask Us to delete any personal data We hold about you;",
        "4.1.5 The right to restrict (i.e. prevent) the processing of your personal data;",
        "4.1.6 The right to data portability (obtaining a copy of your personal data to re-use with another service or organisation);",
        "4.1.7 The right to object to Us using your personal data for particular purposes; and",
        "4.1.8 Rights with respect to automated decision making and profiling.",
        ,<SpaceBr/>,
    
    
    
        ,<SpaceBr/>,
        ,<h2><span>5. What Data Do We Collect?</span></h2>,
        ,<SpaceBr/>,
        "Depending upon your use of Our Site, We may collect some or all of the following personal and non-personal data (please also see section 12 on Our use of Cookies and similar technologies:",
        "5.1 name;",
        "5.2 date of birth;",
        "5.3 gender;",
        "5.4 business/company name",
        "5.5 job title;",
        "5.6 profession;",
        "5.7 contact information such as email addresses and telephone numbers;",
        "5.8 demographic information such as post code, preferences, and interests;",
        "5.9 financial information such as credit / debit card numbers;",
        "5.10 IP address;",
        "5.11 web browser type and version;",
        "5.12 operating system;",
        "5.13 a list of URLs starting with a referring site, your activity on Our Site, and the site you exit to;",
        ,<SpaceBr/>,
    
    
        ,<SpaceBr/>,
        ,<h2><span>6. How Do We Use Your Data?</span></h2>,
        ,<SpaceBr/>,
        "6.1 All personal data is processed and stored securely, for no longer than is necessary in light of the reason(s) for which it was first collected. We will comply with Our obligations and safeguard your rights under the GDPR at all times. 6.2 Our use of your personal data will always have a lawful basis, either because it is necessary for Our performance of a contract with you, because you have consented to Our use of your personal data (e.g. by subscribing to emails), or because it is in Our legitimate interests. Specifically, We may use your data for the following purposes: 6.2.1 Providing and managing your Account; 6.2.2 Providing and managing your access to Our Site; 6.2.3 Personalising and tailoring your experience on Our Site; 6.2.4 Supplying Our services to you (please note that We require your personal data in order to enter into a contract with you); 6.2.5 Personalising and tailoring Our services for you; 6.2.6 Replying to emails from you; 6.2.7 Supplying you with emails that you have opted into (you may unsubscribe or opt-out at any time via the link on the marketing emails. 6.2.8 Market research; 6.2.9 Analysing your use of Our Site and gathering feedback to enable Us to continually improve Our Site and your user experience; 6.3 Third parties whose content appears on Our Site may use third party Cookies, as detailed below in section 12. Please refer to section 12 for more information on controlling Cookies. Please note that We do not control the activities of such third parties, nor the data they collect and use and advise you to check the privacy policies of any such third parties. 6.4 You have the right to withdraw your consent to Us using your personal data at any time, and to request that We delete it."
        ,<SpaceBr/>,
    
    
        ,<SpaceBr/>,
        ,<h2><span>7. Do We Share Your Data?
        </span></h2>,
        ,<SpaceBr/>,
        "7.1 We may share your data with other companies in Our group. This includes Our subsidiaries AND/OR Our holding company and its subsidiaries. 7.2 We may sometimes contract with third parties to supply products and services to you on Our behalf. These may include payment processing, delivery of goods, search engine facilities, advertising, and marketing. In some cases, the third parties may require access to some or all of your data. Where any of your data is required for such a purpose, We will take all reasonable steps to ensure that your data will be handled safely, securely, and in accordance with your rights, Our obligations, and the obligations of the third party under the law. 7.3 We may compile statistics about the use of Our Site including data on traffic, usage patterns, user numbers, sales, and other information. All such data will be anonymised and will not include any personally identifying data, or any anonymised data that can be combined with other data and used to identify you. We may from time to time share such data with third parties such as prospective investors, affiliates, partners, and advertisers. Data will only be shared and used within the bounds of the law. 7.4 In certain circumstances, We may be legally required to share certain data held by Us, which may include your personal data, for example, where We are involved in legal proceedings, where We are complying with legal requirements, a court order, or a governmental authority."
        ,<SpaceBr/>,
    
        ,<SpaceBr/>,
        ,<h2><span>8. What Happens If Our Business Changes Hands?</span></h2>,
        ,<SpaceBr/>,
        "8.1 We may, from time to time, expand or reduce Our business and this may involve the sale and/or the transfer of control of all or part of Our business. Any personal data that you have provided will, where it is relevant to any part of Our business that is being transferred, be transferred along with that part and the new owner or newly controlling party will, under the terms of this Privacy Policy, be permitted to use that data only for the same purposes for which it was originally collected by Us. 8.2 In the event that any of your data is to be transferred in such a manner, you will not be contacted in advance and informed of the changes. When contacted you will not, however, be given the choice to have your data deleted or withheld from the new owner or controller."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>9. How Can You Control Your Data?</span></h2>,
        ,<SpaceBr/>,
        "9.1 In addition to your rights under the GDPR, set out in section 4, when you submit personal data via Our Site, you may be given options to restrict Our use of your data. In particular, We aim to give you strong controls on Our use of your data for direct marketing purposes (including the ability to opt-out of receiving emails from Us which you may do by unsubscribing using the links provided in Our emails and at the point of providing your details and by managing your Account)."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>10. Your Right to Withhold Information</span></h2>,
        ,<SpaceBr/>,
        "10.1 You may access certain areas of Our Site without providing any data at all. However, to use all features and functions available on Our Site you may be required to submit or allow for the collection of certain data."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>11. How Can You Access Your Data?</span></h2>,
        ,<SpaceBr/>,
        "You have the right to ask for a copy of any of your personal data held by Us (where such data is held)."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>12. Our Use of Cookies</span></h2>,
        ,<SpaceBr/>,
        "Our Site may place and access certain first party Cookies on your computer or device. First party Cookies are those placed directly by Us and are used only by Us. We use Cookies to facilitate and improve your experience of Our Site and to provide and improve Our services. By using Our Site you may also receive certain third party Cookies on your computer or device. Third party Cookies are those placed by websites, services, and/or parties other than Us. Third party Cookies are used on Our Site for behavioural, and advertising services. In addition, Our Site uses analytics services provided by, which also use Cookies. Website analytics refers to a set of tools used to collect and analyse usage statistics, enabling Us to better understand how people use Our Site."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>13. Contacting Us</span></h2>,
        ,<SpaceBr/>,
        "If you have any questions about Our Site or this Privacy Policy, please contact Us by email at info@RankLogo.com. Please ensure that your query is clear, particularly if it is a request for information about the data We hold about you (as under section 12, above)."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>14. Changes to Our Privacy Policy</span></h2>,
        ,<SpaceBr/>,
        "We may change this Privacy Policy from time to time (for example, if the law changes). Any changes will be immediately posted on Our Site and you will be deemed to have accepted the terms of the Privacy Policy on your first use of Our Site following the alterations. We recommend that you check this page regularly to keep up-to-date."
        ]}
        ListItem01= ""
        ListItem02= "Abstract Logo"
        ListItem03= "Animated Logo"
        ListItem04= "Illustrative Logo"
        ListItem05= "Branding"
        ListItem06= "Website Design"
        ListItem07= "Video Animation"
        ListItem08= "Digital Marketing"
        ButtonLightLink= "tel:+44 07927768154"
        ButtonLightTitle= "+44 07927768154"
      />
      
    </main>
  )
}
export default Privacy;