import Head from 'next/head'
import styles from '../../styles/Style.module.css'
import AboutSec from '../../components/AboutSec'
import { SpaceBr } from '../../components/Space'



const Terms =()=> {
  return (
    <main className={styles.TermsPage}>
      <Head>
        <title>RankLogo</title>
        <meta name="description" content="Generated by create next app" />  
      </Head>

      <AboutSec
        BackgroundImage= ""
        Title={["Terms Of Use"]}
        SubTitle={["1. DEFINITIONS"]}
        Para={["1.1 The following words shall have the following meanings: Agent: an agent appointed to act on the Artist’s behalf; Artist: a person who provides artwork; Artwork: the artwork which is created from the job description set out on the client order confirmation; Client: a person, firm or company who commissions the Artwork; Client Order Confirmation: the order confirmation sheet; Contract: these terms and the Client Order Confirmation; Fee: as defined in clause 6. Licensed Rights: the grant of the right to use the Artwork as set out on the Client Order Confirmation; Territory, Bank Account, Job Description: as defined on the Client Order Confirmation. 1.2 A person includes a natural person, corporate or unincorporated body (whether or not having separate legal personality). 1.3 In these Terms the singular includes the plural and vice versa.",

        ,<SpaceBr/>,
        ,<h2><span>2. ARTIST AND AGENCY'S OBLIGATIONS</span></h2>,
        ,<SpaceBr/>,
        "2.1 The Artist agrees to provide the Artwork in accordance with this Contract. 2.2 The Agency acts solely as the agent of the Artist and confirms that it is authorised to enter into this Contract on behalf of the Artist. 2.3 This Contract is between the Artist and the Client. The Client agrees that all communications relating to the Artwork shall be made only to the Agency. The Client accepts that the Agency, except as specifically provided, assumes no liability under this Contract and accordingly is not liable for the acts or omissions of the Artist. 2.4 The Artist shall use reasonable endeavours to meet any performance dates specified in the Client Order Confirmation but any such dates shall be estimates only and time shall not be of the essence for performance of the artwork."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>3. CLIENT'S OBLIGATIONS</span></h2>,
        ,<SpaceBr/>,
        "3.1 The Client shall: (a) co-operate with the Artist and the Agency in all matters relating to the Artwork; (b) approve roughs and supply reference material; (c) keep and maintain the Artwork in good condition, not use the Artwork other than in accordance with the Agency's Client Order Confirmation or other written authorisation; and (d) pay the Fee. 3.2 The person signing the Contract on behalf of the Client confirms that they have the requisite power and authority to enable them to enter into and perform this Contract and further confirms that they accept full responsibility for the payment of fees. 3.3 The Client shall be liable to pay to the Agency, on demand, all reasonable costs, charges or losses sustained or incurred by the Artist and the Agency arising directly or indirectly from the Client's fraud, negligence, failure to perform or delay in the performance of any of its obligations under this Contract, subject to the Agency confirming such costs, charges and losses to the Client in writing."
        ,<SpaceBr/>,

        

        ,<SpaceBr/>,
        ,<h2><span>4. COOKIES</span></h2>,
        ,<SpaceBr/>,
        "4.1 Cookies are small text files that are stored on your computer, tablet or phone when you visit a website. We use cookies to help you navigate our website, for example by remembering your preferences, authenticating your logins and recording what you have put in your client area. 4.2 We also use cookies to understand how visitors use our website because it helps us to find ways to improve it. For example, a cookie might tell us that lots of people give up on an enquiry process at a particular step and that information helps us to make that step easier to use."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>5. APPLICATION OF TERMS</span></h2>,
        ,<SpaceBr/>,
        "5.1 These Terms shall: (a) apply to and be incorporated into this Contract; and (b) prevail over any prior or retrospective inconsistent term or terms contained, or referred to, in the Client's purchase order, confirmation of order, acceptance of a quotation, or implied by law, trade custom, practice or course of dealing. 5.2 No offer placed by the Client for any artwork shall be accepted by the Artist other than: (a) by a Client Order Confirmation; (b) by a purchase order signed by the Client accepting these Terms; or (c) (if earlier) by the Artist starting to produce Artwork having received either written or verbal permission to start, when a contract for the supply and purchase of the Artwork on these Terms will be established. 5.3 Estimates are given by the Agency on the basis that no Contract shall come into existence except in accordance with condition 4.2."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>6. DELIVERY</span></h2>,
        ,<SpaceBr/>,
        "6.1 Any dates specified by the Artist or the Agency for delivery of the Artwork are intended to be an estimate only and time for delivery shall not be made of the essence by notice. If no dates are so specified, delivery shall be within a reasonable time and will be subject to the Client complying with its obligations. If the work is delivered electronically it will be deemed finished if either high or low resolution. 6.2 Requests for amendments made later than: (a) three working days after the delivery of Artwork may be refused by the Artist where they may interfere with subsequent commissions. In this case, no reduction in fee will be allowed; or (b) seven days after the delivery of the Artwork will be refused by the Artist and it shall be conclusively presumed that the Artwork has been accepted."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>7. FEES</span></h2>,
        ,<SpaceBr/>,
        "7.1 All payments shall be made to the Agency whose receipt shall be a full and sufficient discharge to the Client. 7.2 The Client shall pay the fees set out on the Client Order Confirmation, on a purchase order or if the Contract was formed in accordance with clause 4.2(c), the fees either confirmed in writing by email or fax, or agreed orally prior to the Artist producing the Artwork (the Fee). 7.3 Any request for additional use of the Artwork shall be made in accordance with condition 10. 7.4 The Artwork will be supplied in paper form or digitally. If extra electronic or digital copies or prints are required additional fees will be charged. 7.5 All sums payable to the Artist or the Agency under this Contract shall become due immediately on its termination, despite any other provision. 7.6 The Client may not set off any liability to the Artist or Agency against sums due to any other artist represented by the Agency. 7.7 The Agency may, without prejudice to any other rights it may have, set off any liability of the Client to the Artist or Agency against any liability of the Artist or Agency to the Client."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>8. INTELLECTUAL PROPERTY RIGHTS</span></h2>,
        ,<SpaceBr/>,
        "8.1 The Artist grants to the Client the Licensed Rights and, unless otherwise agreed in writing, remains the owner of all other intellectual property rights in the Artwork (including electronic versions) such rights being protected worldwide. 8.2 The Artist asserts his moral rights in relation to the Artwork. 8.3 The Licensed Rights include the right to print off copies and download extracts, of the artwork for the purpose of exercising the Licensed Rights. 8.4 Unless otherwise agreed in writing, the Client (including its employees and subcontractors) must not modify Artwork in any way, nor use any illustrations, photographs or any graphics in alternative formats, media or extracts not specifically included in the Licensed Rights. 8.5 Any loss, damage or alteration to the Artwork whilst in the possession or control of the Client will be charged at a fee not less than the Fee. 8.6 The Licensed Rights are granted on an exclusive licence in the Territory. The Licensed Rights are only granted once payment is received in accordance with condition 6. Any permission for prior use without payment will be revoked if payment is not received in full on the date due, or if the contract is terminated in accordance with condition 9.2. 8.7 Unless otherwise agreed in writing, supply by the Artist of any electronic image in separated or layered form shall not grant the Client the right to use the separated material. 8.8 If the Contract terminates, the Licensed Rights shall automatically terminate. 8.9 The Client may not sub-licence the Artwork to third parties without the prior written consent of the Artist. 8.10 The Client warrants that all information and reference materials provided to the Artist or Agent will not infringe the intellectual property rights of any third party. 8.11 Unless otherwise agreed in writing, the Client agrees that it will not instruct third parties to produce artwork which is the same as or similar to the Artwork."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>9. LIMITATION OF LIABILITY</span></h2>,
        ,<SpaceBr/>,
        "9.1 This condition 8 sets out the entire financial liability of the Artist and the Agency (including any liability for the acts or omissions of its employees, agents, consultants, and subcontractors) to the Client in respect of any breach of the Contract and any representation, statement or tortious act or omission (including negligence) arising under or in connection with the Contract. 9.2 All warranties, terms and other terms implied by statute or common law are, to the fullest extent permitted by law, excluded from the Contract. 9.3 Nothing in these Terms limits or excludes the liability of the Artist or the Agency for death or personal injury resulting from negligence, fraud or fraudulent misrepresentation. 9.4 Subject to condition 8.2 and condition 8.3: (a) neither the Artist nor the Agency shall be liable for: loss of profits; loss of business; depletion of goodwill and/or similar losses; loss of anticipated savings; loss of goods; loss of contract; loss of use; loss of corruption of data or information; any special, indirect, consequential or pure economic loss, costs, damages, charges or expenses; and (b) total liability of both the Artist and Agency in contract, tort (including negligence or breach of statutory duty), misrepresentation, restitution or otherwise arising in connection with the performance, or contemplated performance, of this Contract shall be limited to the price paid for the Artwork."
        ,<SpaceBr/>,


        ,<SpaceBr/>,
        ,<h2><span>10. TERMINATION AND REJECTION</span></h2>,
        ,<SpaceBr/>,
        "10.1 The Client may terminate this Contract at any time. 10.2 Either party may terminate this Contract forthwith on giving notice in writing to the other if one party ceases to carry on business or commits any material breach of any term of this Contract and (in the case of a breach capable of being remedied) shall have failed, within 7 days after the receipt of the request in writing from the other to do so, to remedy the breach. 10.3 If the Contract is terminated prior to acceptance of the Artwork the following percentages of the Fee will be payable: (a) The following percentages of the Fee; (i) 25% before delivery of roughs; (ii) 33% after delivery of roughs; (iii) 50% after delivery of colour visual; (iv) 75% after delivery of any subsequent revised illustration rough; (v) 100% on delivery of the finished artwork; or (vi) pro rata if at an intermediate stage; and (b) If the Artist has refused to accept further commissions from third parties, for the period in which the Artist has allotted to producing the Artwork, the Artist retains the right to claim against the Client in respect of those losses. Such claim for losses together with the amount set out at condition 9.3(a) shall not exceed 100% of the Fee. 10.4 Notwithstanding the above, 100% of the Fee will be payable if: (a) the Client uses the Artwork for the purpose set out in the Job Description; or (b) the Artist has correctly followed the Job Description and the work is consistent with that of the Artist's portfolio, and with that shown to the Client. The Client acknowledges that rejection is not permitted on the basis of style or composition. 10.5 The Client shall return all original artwork and samples no later than six months after delivery. In any event, the Client shall return the Artwork immediately on termination."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>11. VARIATION</span></h2>,
        ,<SpaceBr/>,
        "No variation of the Contract or these Terms, (which includes a request for additional or extra work), shall be valid unless it is in writing and signed by or on behalf of the Client and the Agency. Any variation of the terms may be subject to the payment of an additional fee. The Artist retains the right to charge for any variation in the Artwork."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>12. ENTIRE AGREEMENT</span></h2>,
        ,<SpaceBr/>,
        "The Contract constitutes the whole agreement between the parties and supersedes all previous agreements between the parties relating to its subject matter."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>13. ASSIGNMENT</span></h2>,
        ,<SpaceBr/>,
        "The Client shall not, without the prior written consent of the Agency, assign or deal in any other manner with all or any of its rights or obligations under the Contract."
        ,<SpaceBr/>,

        ,<SpaceBr/>,
        ,<h2><span>14. ORDERS PROCESSED</span></h2>,
        ,<SpaceBr/>,
        "The turnaround time of your order is dependent on the following factors: 1. The style of illustration and details 2. The number of requests you have in queue 3. The level of project/request complexity It will take four working days to deliver the first concept after the order is placed with us. However, the revisions may take 2-4 business days. Revisions are considered as new request and may change the overall timeline of the project."
        ,<SpaceBr/>,


        ]}
        ListItem01= ""
        ListItem02= "Abstract Logo"
        ListItem03= "Animated Logo"
        ListItem04= "Illustrative Logo"
        ListItem05= "Branding"
        ListItem06= "Website Design"
        ListItem07= "Video Animation"
        ListItem08= "Digital Marketing"
        ButtonLightLink= "tel:+44 07927768154"
        ButtonLightTitle= "+44 07927768154"
      />
      
    </main>
  )
}
export default Terms;