import Head from 'next/head'
import styles from '../../styles/Style.module.css'
import LeaderShipSec from '../../components/LeaderShipSec'
import TestimonialSec from '../../components/TestimonialSec'
import ContactSec from '../../components/ContactSec'
import BannerGlobal from '../../components/BannerGlobal'
import TechnologiesContent from '../../components/TechnologiesContent'

const Technologies =()=> {
  return (
    <main className={[styles.InnerPage]+" "+[styles.TechnologiesPage]}>
      <Head>
        <title>Technologies | Rank Logo</title>
        <meta name="description" content="Generated by create next app" />  
      </Head>

      <BannerGlobal
      BackgroundImage= "url(./assets/banner/7.jpg)"
      Title= "The Use of Cutting-edge Technology"
      Para= "At Logo Frank, we articulate your exceptional brand perception with the use of avant-garde technologies."
      />
      <TechnologiesContent/>
      <LeaderShipSec/>
      <TestimonialSec/>
      <ContactSec/>
    </main>
  )
}
export default Technologies;