import Head from 'next/head'
import styles from '../../styles/Style.module.css'
import LeaderShipSec from '../../components/LeaderShipSec'
import TestimonialSec from '../../components/TestimonialSec'
import ContactSec from '../../components/ContactSec'
import BannerGlobal from '../../components/BannerGlobal'
import AboutSec from '../../components/AboutSec'
import ValueSec from '../../components/ValueSec'

const About =()=> {
  return (
    <main className={[styles.InnerPage]+" "+[styles.AboutPage]}>
      <Head>
        <title>About Us | Rank Logo</title>
        <meta name="description" content="Generated by create next app" />  
      </Head>

      <BannerGlobal
      BackgroundImage= "url(./assets/banner/6.jpg)"
      Title= "A Top-Notch Digital Design Agency"
      Para= "Rank Logo is one of the recognized and renowned digital design agency. At Rank Logo, we offer one-stop digital-branding solutions."
      />

      <AboutSec
        BackgroundImage= "url('assets/modal/9.jpg')"
        Title="About Us"
        SubTitle="We craft an aesthetic experience that never existed before"
        Para="Every business's online presence plays a vital role in brand image and its identity. That's why our clients trust us, and we gave them the best logo designing services according to their brand requirements. Our logo designers experts examine your business niche and recommend how your business should go with its image. Our logo designers create appealing logo samples for your business, and then it's up to you what you select for your brand. We have expertise in designing attractive and stunning logos for all companies. If you start a business, first work on its image, which means the Logo. We provide different types of logo designs;
        "
        Para2={["RankLogo is a logo designing agency which provides the creative and innovative logo designs to the customers of all business niches. Our logo designer’s experts know how to create excellent logos and deliver them on time without any hassle. You can trust our agency if you want to take your business to the highest level with impressive and stunning logos. Our logo designers are work on the Logo for your business that resonates with your services/products and help in attracting more customers."]}

        ListItem01= "Versatile Logo "
        ListItem02= "Minimalist Logo "
        ListItem03= "Monogram/Initial Logo"
        ListItem04= "Signature Logo"
        ListItem05= "Vintage Logo        "
        ListItem06= "Website Design"
        ListItem07= "Video Animation"
        ListItem08= "Digital Marketing"
        
        ButtonDarkLink= "#"
        ButtonDarkTitle= "Get a Design Now"
        ButtonLightLink= "tel:+44 07927768154"
        ButtonLightTitle= "+44 07927768154"
      />

      <ValueSec />

      <LeaderShipSec/>
      <TestimonialSec/>
      <ContactSec/>
    </main>
  )
}
export default About;